export const FETCH_FIRST_QUESTION_REQUEST = "FETCH_FIRST_QUESTION_REQUEST" ; 
export const FETCH_FIRST_QUESTION_SUCCESS = "FETCH_FIRST_QUESTION_SUCCESS" ; 
export const FETCH_FIRST_QUESTION_ERROR = "FETCH_FIRST_QUESTION_ERROR" ;   

export const FETCH_NEXT_SET_REQUEST = "FETCH_NEXT_SET_REQUEST" ; 
export const FETCH_NEXT_SET_SUCCESS = "FETCH_NEXT_SET_SUCCESS" ;  
export const FETCH_NEXT_SET_ERROR = "FETCH_NEXT_SET_ERROR" ;    

export const FETCH_REPORT_REQUEST  = "FETCH_REPORT_REQUEST" ; 
export const FETCH_REPORT_SUCCESS  = "FETCH_REPORT_SUCCESS" ; 
export const FETCH_REPORT_ERROR  = "FETCH_REPORT_ERROR" ; 
