export const NEW_ACCESS_DOMAIN = "NEW_ACCESS_DOMAIN" ; 
export const TEST_3_STARTING = "TEST_3_STARTING" ;   
export const TEST_3_COMPLETED = "TEST_3_COMPLETED" ;  
export const NEW_ACCESS_DOMAIN_FAILED = "NEW_ACCESS_DOMAIN_FAILED" ; 
