export const TEST_1_STARTING = "TEST_1_STARTING" ; 
export const FILE_DOWNLOAD_TESTING = "FILE_DOWNLOAD_TESTING"; 
export const TEST_2_STARTING = "TEST_2_STARTING" ; 
export const TEST_2_COMPLETED = "TEST_2_COMPLETED" ; 
export const TEST_1_COMPLETED = "TEST_1_COMPLETED" ; 